#!/usr/bin/env python3
"""
Test Matrix Tool — init + check

Usage:
  generate.py init config.json          # scaffold from config
  echo '{...}' | generate.py init -     # scaffold from stdin
  generate.py check tests/e2e/          # validate coverage
"""
import ast
import json
import os
import re
import sys
from textwrap import dedent


# ══════════════════════════════════════════
# init: scaffold pytest structure from config
# ══════════════════════════════════════════

def cmd_init(config):
    name = config.get("name", "test-matrix")
    output_dir = config.get("output_dir", "tests/e2e")
    # Python 패키지는 하이픈 불가 → 마지막 경로 세그먼트를 언더스코어로 변환
    parent, leaf = os.path.split(output_dir.rstrip("/"))
    sanitized_leaf = leaf.replace("-", "_")
    if sanitized_leaf != leaf:
        output_dir = os.path.join(parent, sanitized_leaf)
        print(f"note: renamed '{leaf}' → '{sanitized_leaf}' (Python package)")
    flows = config.get("flows", [])
    axes = config.get("axes", [])
    api_config = config.get("api")

    if not flows:
        print("Error: 'flows' is required", file=sys.stderr)
        sys.exit(1)
    if not axes:
        print("Error: 'axes' is required", file=sys.stderr)
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    written = []

    # __init__.py
    init_path = os.path.join(output_dir, "__init__.py")
    if not os.path.exists(init_path):
        _write(init_path, "")
        written.append("__init__.py")

    # mocks.py
    _write(os.path.join(output_dir, "mocks.py"), _gen_mocks(axes))
    written.append("mocks.py")

    # logic.py
    _write(os.path.join(output_dir, "logic.py"), _gen_logic(flows))
    written.append("logic.py")

    # conftest.py
    _write(os.path.join(output_dir, "conftest.py"), _gen_conftest(axes, api_config))
    written.append("conftest.py")

    # test_flows.py
    _write(os.path.join(output_dir, "test_flows.py"), _gen_test_flows(name, flows, axes, api_config))
    written.append("test_flows.py")

    # common.py (api only)
    if api_config:
        _write(os.path.join(output_dir, "common.py"), _gen_common(api_config))
        written.append("common.py")

    # summary
    mock_combos = 1
    for a in axes:
        mock_combos *= len(a.get("items", []))
    mock_tests = len(flows) * mock_combos
    api_tests = mock_tests if api_config else 0

    print(f"init: {output_dir}/")
    print(f"  flows: {', '.join(flows)}")
    axis_summary = " x ".join(f"{a['name']}({len(a.get('items', []))})" for a in axes)
    print(f"  axes:  {axis_summary}")
    print(f"  mock tests:  {mock_tests}")
    if api_tests:
        print(f"  api tests:   {api_tests}")
    print(f"  total slots: {mock_tests + api_tests}")
    print(f"  files: {', '.join(written)}")


def _write(path, content):
    with open(path, "w") as f:
        f.write(content)


def _gen_mocks(axes):
    lines = [
        '"""',
        "Mock data — auto-generated by test-matrix.",
        "Fill in mock values for each item.",
        '"""',
        "",
    ]
    for axis in axes:
        name = axis["name"]
        upper = name.upper()
        items = axis.get("items", [])

        lines.append(f"# {'=' * 40}")
        lines.append(f"# {name}")
        lines.append(f"# {'=' * 40}")
        lines.append(f"{upper}S = [")
        for item in items:
            lines.append("    {")
            lines.append(f'        "id": "{item["id"]}",')
            lines.append(f'        "desc": "{item.get("desc", item["id"])}",')
            lines.append("        # TODO: add mock data fields")
            lines.append("    },")
        lines.append("]")
        lines.append(f'{upper}_IDS = [m["id"] for m in {upper}S]')
        lines.append("")
    return "\n".join(lines) + "\n"


def _gen_logic(flows):
    lines = [
        '"""',
        "Business logic — auto-generated by test-matrix.",
        "Reproduce the source code logic here for test verification.",
        '"""',
        "",
    ]
    for flow in flows:
        lines.append(f"def {flow}(mock_data):")
        lines.append(f'    """TODO: implement {flow} logic"""')
        lines.append("    raise NotImplementedError")
        lines.append("")
    return "\n".join(lines) + "\n"


def _gen_conftest(axes, api_config):
    lines = [
        '"""',
        "pytest fixtures — auto-generated by test-matrix.",
        '"""',
        "import pytest",
    ]
    if api_config:
        lines.append("from .common import api_get")
    lines += ["", ""]

    if api_config:
        lines.append("# Session fixtures — called once, reused across all tests")
        for axis in axes:
            name = axis["name"]
            lines.append(f'@pytest.fixture(scope="session")')
            lines.append(f"def {name}_data():")
            lines.append(f'    """TODO: fetch {name} data from API"""')
            lines.append(f"    return {{}}")
            lines.append("")
    return "\n".join(lines) + "\n"


def _gen_test_flows(name, flows, axes, api_config):
    dims = " x ".join(str(len(a.get("items", []))) for a in axes)
    lines = [
        '"""',
        f"{name} — {len(flows)} Flows x {dims} items",
        "",
        "Auto-generated by test-matrix.",
        '"""',
        "import pytest",
        "",
    ]

    # imports
    mock_imports = []
    for axis in axes:
        upper = axis["name"].upper()
        mock_imports.append(f"{upper}S")
        mock_imports.append(f"{upper}_IDS")
    lines.append(f"from .mocks import {', '.join(mock_imports)}")
    lines.append(f"from .logic import {', '.join(flows)}")
    if api_config:
        lines.append("from .common import api_get, api_post")
    lines += ["", ""]

    # mock tests
    lines.append(f"# {'=' * 50}")
    lines.append("# Mock tests")
    lines.append(f"# {'=' * 50}")
    for flow in flows:
        for axis in axes:
            upper = axis["name"].upper()
            lines.append(f'@pytest.mark.parametrize("{axis["name"]}", {upper}S, ids={upper}_IDS)')
        params = ", ".join(a["name"] for a in axes)
        lines.append(f"def test_mock_{flow}({params}):")
        lines.append(f"    # TODO: call {flow}() and assert")
        lines.append(f"    result = {flow}({axes[0]['name']})")
        lines.append("    assert result is not None")
        lines.append("")

    # api tests
    if api_config:
        lines.append(f"# {'=' * 50}")
        lines.append("# API E2E tests")
        lines.append(f"# {'=' * 50}")
        for flow in flows:
            for axis in axes:
                upper = axis["name"].upper()
                lines.append(f'@pytest.mark.parametrize("{axis["name"]}", {upper}S, ids={upper}_IDS)')
            mock_params = ", ".join(a["name"] for a in axes)
            fix_params = ", ".join(f"{a['name']}_data" for a in axes)
            lines.append(f"def test_api_{flow}({mock_params}, {fix_params}):")
            lines.append("    # TODO: call API and verify")
            lines.append("    pytest.skip('not implemented')")
            lines.append("")

    return "\n".join(lines) + "\n"


def _gen_common(api_config):
    base_url_env = api_config.get("base_url_env", "API_BASE_URL")
    token_env = api_config.get("token_env", "API_TOKEN")
    return dedent(f'''\
        """
        HTTP helpers — auto-generated by test-matrix.
        """
        import os
        import urllib.request
        import json

        BASE_URL = os.environ.get("{base_url_env}", "http://localhost:3000")
        TOKEN = os.environ.get("{token_env}", "REPLACE_ME")

        HEADERS = {{
            "Content-Type": "application/json",
            "Authorization": f"Bearer {{TOKEN}}",
        }}


        def api_get(path: str) -> dict | list:
            req = urllib.request.Request(f"{{BASE_URL}}{{path}}", headers=HEADERS)
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read())


        def api_post(path: str, body: dict) -> dict:
            data = json.dumps(body).encode()
            req = urllib.request.Request(
                f"{{BASE_URL}}{{path}}", data=data, headers=HEADERS, method="POST"
            )
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read())
    ''')


# ══════════════════════════════════════════
# check: validate matrix coverage
# ══════════════════════════════════════════

def cmd_check(test_dir):
    test_file = os.path.join(test_dir, "test_flows.py")
    mocks_file = os.path.join(test_dir, "mocks.py")

    if not os.path.exists(test_file):
        print(f"Error: {test_file} not found", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(mocks_file):
        print(f"Error: {mocks_file} not found", file=sys.stderr)
        sys.exit(1)

    # parse mocks.py — find all *S = [...] and count items
    axes = _parse_mock_axes(mocks_file)
    # parse test_flows.py — find all test functions and their parametrize decorators
    tests = _parse_test_functions(test_file)

    if not axes:
        print("Warning: no mock axes found in mocks.py")
        return
    if not tests:
        print("Warning: no test functions found in test_flows.py")
        return

    # calculate coverage
    total_combos = 1
    for axis_name, count in axes.items():
        total_combos *= count

    print(f"check: {test_dir}/")
    print(f"  axes:")
    for axis_name, count in axes.items():
        print(f"    {axis_name}: {count} items")
    print(f"  combinations per flow: {total_combos}")
    print()

    mock_tests = [t for t in tests if t["name"].startswith("test_mock_")]
    api_tests = [t for t in tests if t["name"].startswith("test_api_")]

    print(f"  mock tests: {len(mock_tests)} functions")
    for t in mock_tests:
        flow = t["name"].removeprefix("test_mock_")
        covered = _calc_coverage(t["parametrize"], axes)
        status = "OK" if covered == total_combos else f"GAP ({covered}/{total_combos})"
        missing_axes = [a for a in axes if a not in t["parametrize"]]
        if missing_axes:
            status = f"MISSING AXES: {', '.join(missing_axes)}"
        print(f"    {flow}: {status}")

    if api_tests:
        print(f"  api tests:  {len(api_tests)} functions")
        for t in api_tests:
            flow = t["name"].removeprefix("test_api_")
            covered = _calc_coverage(t["parametrize"], axes)
            status = "OK" if covered == total_combos else f"GAP ({covered}/{total_combos})"
            missing_axes = [a for a in axes if a not in t["parametrize"]]
            if missing_axes:
                status = f"MISSING AXES: {', '.join(missing_axes)}"
            print(f"    {flow}: {status}")

    total_test_slots = (len(mock_tests) + len(api_tests)) * total_combos
    actual_slots = sum(_calc_coverage(t["parametrize"], axes) for t in tests)
    pct = (actual_slots / total_test_slots * 100) if total_test_slots else 0
    print()
    print(f"  coverage: {actual_slots}/{total_test_slots} ({pct:.0f}%)")


def _parse_mock_axes(filepath):
    """Parse mocks.py to find axes: FOOS = [...] → {"foo": count}"""
    axes = {}
    with open(filepath) as f:
        content = f.read()

    # find patterns like MEMBER_TYPES = [ ... ]
    pattern = re.compile(r"^([A-Z][A-Z0-9_]*S)\s*=\s*\[", re.MULTILINE)
    for match in pattern.finditer(content):
        var_name = match.group(1)
        # skip _IDS variables
        if var_name.endswith("_IDS"):
            continue
        # count items by finding dicts in the list
        start = match.end()
        bracket_depth = 1
        items = 0
        i = start
        while i < len(content) and bracket_depth > 0:
            ch = content[i]
            if ch == "[":
                bracket_depth += 1
            elif ch == "]":
                bracket_depth -= 1
            elif ch == "{" and bracket_depth == 1:
                items += 1
            i += 1

        # convert VAR_NAMES → var_name (strip trailing S, lowercase)
        axis_name = var_name[:-1].lower()  # MEMBER_TYPES → member_type
        axes[axis_name] = items

    return axes


def _parse_test_functions(filepath):
    """Parse test_flows.py to find test functions and their parametrize decorators."""
    tests = []
    with open(filepath) as f:
        content = f.read()

    try:
        tree = ast.parse(content)
    except SyntaxError:
        print(f"Warning: could not parse {filepath}", file=sys.stderr)
        return tests

    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        if not node.name.startswith("test_"):
            continue

        parametrize = {}
        for dec in node.decorator_list:
            if not isinstance(dec, ast.Call):
                continue
            func = dec.func
            # match pytest.mark.parametrize
            if isinstance(func, ast.Attribute) and func.attr == "parametrize":
                if dec.args and isinstance(dec.args[0], ast.Constant):
                    param_name = dec.args[0].value
                    # try to get the variable name to count items
                    if len(dec.args) > 1 and isinstance(dec.args[1], ast.Name):
                        parametrize[param_name] = dec.args[1].id

        tests.append({"name": node.name, "parametrize": parametrize})

    return tests


def _calc_coverage(parametrize_map, axes):
    """Calculate how many combinations a test covers based on its parametrize decorators."""
    covered = 1
    for axis_name, count in axes.items():
        if axis_name in parametrize_map:
            covered *= count
        # if axis not parametrized, it covers 1 (fixed value)
    return covered


# ══════════════════════════════════════════
# CLI
# ══════════════════════════════════════════

def main():
    if len(sys.argv) < 2:
        print(__doc__.strip())
        sys.exit(1)

    command = sys.argv[1]

    if command == "init":
        if len(sys.argv) < 3:
            print("Usage: generate.py init <config.json | ->", file=sys.stderr)
            sys.exit(1)
        source = sys.argv[2]
        if source == "-":
            config = json.load(sys.stdin)
        else:
            with open(source) as f:
                config = json.load(f)
        cmd_init(config)

    elif command == "check":
        if len(sys.argv) < 3:
            print("Usage: generate.py check <test_dir>", file=sys.stderr)
            sys.exit(1)
        cmd_check(sys.argv[2])

    else:
        print(f"Unknown command: {command}", file=sys.stderr)
        print("Commands: init, check", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
