#!/usr/bin/env python3
"""
Test Matrix Tool — scenario-based test scaffold + coverage check

Usage:
  generate.py init config.json          # scaffold from config
  echo '{...}' | generate.py init -     # scaffold from stdin
  generate.py check tests/topic/        # validate coverage
"""
import ast
import json
import math
import re
import sys
from pathlib import Path
from textwrap import dedent


# ══════════════════════════════════════════
# Templates
# ══════════════════════════════════════════

MOCKS_HEADER = dedent('''\
    """
    Mock data (Given state) — auto-generated by test-matrix.
    Fill in realistic mock values based on Postman API responses.
    """
''')

LOGIC_HEADER = dedent('''\
    """
    Scenario logic (When step) — auto-generated by test-matrix.
    Port the frontend/backend logic that each scenario exercises.
    """
''')

MOCK_ITEM = '''\
    {{
        "id": "{id}",
        "desc": "{desc}",{fail_line}
        # TODO: add given-state fields
    }},'''

LOGIC_FN = '''\
def {fn}(given_data, variation):
    """
    {desc}{given_line}{when_line}{then_line}
    """
    raise NotImplementedError
'''


# ══════════════════════════════════════════
# init
# ══════════════════════════════════════════

def cmd_init(config):
    name = config.get("name", "test-matrix")
    out = _sanitize_dir(Path(config.get("output_dir", "tests")))
    scenarios = config.get("scenarios", [])

    if not scenarios:
        _die("'scenarios' is required")

    for sc in scenarios:
        if not sc.get("axes"):
            _die(f"scenario '{sc.get('id', '?')}' has no axes")

    out.mkdir(parents=True, exist_ok=True)
    files = {
        "__init__.py": "",
        "mocks.py": _gen_mocks(scenarios),
        "logic.py": _gen_logic(scenarios),
        "test_scenarios.py": _gen_tests(name, scenarios),
    }

    for fname, content in files.items():
        path = out / fname
        if fname == "__init__.py" and path.exists():
            continue
        path.write_text(content)

    # summary
    print(f"init: {out}/")
    total = 0
    for sc in scenarios:
        combos = _count_combos(sc)
        total += combos
        axes_str = " x ".join(f"{a['name']}({len(a.get('items', []))})" for a in sc["axes"])
        print(f"  {sc['id']}: {axes_str} = {combos} cases")
    print(f"  total: {total} cases")
    print(f"  files: {', '.join(files.keys())}")


def _gen_mocks(scenarios):
    parts = [MOCKS_HEADER]
    for sc in scenarios:
        parts.append(f"# {'=' * 50}")
        parts.append(f"# Scenario: {sc.get('desc', sc['id'])}")
        parts.append(f"# {'=' * 50}\n")

        for axis in sc.get("axes", []):
            upper = axis["name"].upper()
            items_str = "\n".join(
                MOCK_ITEM.format(
                    id=item["id"],
                    desc=item.get("desc", item["id"]),
                    fail_line='\n        "expect_fail": True,' if item.get("expect_fail") else "",
                )
                for item in axis.get("items", [])
            )
            parts.append(f"# {axis['name']}")
            parts.append(f"{upper}S = [\n{items_str}\n]")
            parts.append(f'{upper}_IDS = [m["id"] for m in {upper}S]\n')

    return "\n".join(parts) + "\n"


def _gen_logic(scenarios):
    parts = [LOGIC_HEADER]
    for sc in scenarios:
        fn = _slug(sc["id"])
        parts.append(LOGIC_FN.format(
            fn=fn,
            desc=sc.get("desc", sc["id"]),
            given_line=f"\n    Given: {sc['given']}" if sc.get("given") else "",
            when_line=f"\n    When: {sc['when']}" if sc.get("when") else "",
            then_line=f"\n    Then: {sc['then']}" if sc.get("then") else "",
        ))
    return "\n".join(parts) + "\n"


def _gen_tests(name, scenarios):
    # collect imports
    mock_imports = set()
    logic_imports = set()
    for sc in scenarios:
        logic_imports.add(_slug(sc["id"]))
        for axis in sc.get("axes", []):
            upper = axis["name"].upper()
            mock_imports.update([f"{upper}S", f"{upper}_IDS"])

    lines = [
        f'"""\n{name} — scenario-based test matrix\n\nAuto-generated by test-matrix.\n"""',
        "import pytest",
        "",
        f"from .mocks import {', '.join(sorted(mock_imports))}",
        f"from .logic import {', '.join(sorted(logic_imports))}",
        "", "",
    ]

    for sc in scenarios:
        fn = _slug(sc["id"])
        axes = sc.get("axes", [])

        lines.append(f"# {'=' * 50}")
        lines.append(f"# {sc.get('desc', sc['id'])}")
        lines.append(f"# {'=' * 50}\n")

        # parametrize decorators
        for axis in axes:
            upper = axis["name"].upper()
            lines.append(f'@pytest.mark.parametrize("{axis["name"]}", {upper}S, ids={upper}_IDS)')

        params = ", ".join(a["name"] for a in axes)
        lines.append(f"def test_{fn}({params}):")

        if len(axes) == 1:
            v = axes[0]["name"]
            lines.extend([
                f"    if {v}.get('expect_fail'):",
                f"        with pytest.raises(Exception):",
                f"            {fn}({v}, {v})",
                f"    else:",
                f"        result = {fn}({v}, {v})",
                f"        assert result is not None",
            ])
        elif len(axes) > 1:
            variation_inner = ", ".join(f'"{a["name"]}": {a["name"]}' for a in axes)
            lines.extend([
                f"    variation = {{{variation_inner}}}",
                f"    expect_fail = any(v.get('expect_fail') for v in variation.values())",
                f"    if expect_fail:",
                f"        with pytest.raises(Exception):",
                f"            {fn}({axes[0]['name']}, variation)",
                f"    else:",
                f"        result = {fn}({axes[0]['name']}, variation)",
                f"        assert result is not None",
            ])
        else:
            lines.extend([
                f"    result = {fn}({{}}, {{}})",
                f"    assert result is not None",
            ])
        lines.append("")

    return "\n".join(lines) + "\n"


# ══════════════════════════════════════════
# check
# ══════════════════════════════════════════

def cmd_check(test_dir):
    d = Path(test_dir)
    test_file = _find_test_file(d)
    mocks_file = d / "mocks.py"

    if not mocks_file.exists():
        _die(f"{mocks_file} not found")

    axes = _parse_mock_axes(str(mocks_file))
    tests = _parse_test_functions(str(test_file))

    if not axes:
        print("Warning: no mock axes found in mocks.py")
        return
    if not tests:
        print("Warning: no test functions found")
        return

    print(f"check: {test_dir}/")

    # TODO detection
    todos = _detect_todos(d)
    if todos:
        print(f"  unfilled:")
        for t in todos:
            print(f"    ! {t}")
        print()

    print(f"  axes:")
    for axis_name, count in axes.items():
        print(f"    {axis_name}: {count} items")
    print()

    # group by class
    groups = {}
    for t in tests:
        group = t.get("class", "_standalone")
        groups.setdefault(group, []).append(t)

    total_cases = 0
    total_parametrized = 0

    print(f"  scenarios:")
    for group_name, group_tests in groups.items():
        label = group_name if group_name != "_standalone" else "standalone"
        group_cases = 0
        group_axes_used = set()

        for t in group_tests:
            cases = 1
            for param_name, var_name in t["parametrize"].items():
                matched = _match_axis(param_name, var_name, axes)
                if matched:
                    cases *= axes[matched]
                    group_axes_used.add(matched)
            group_cases += cases

        axes_str = ", ".join(sorted(group_axes_used)) if group_axes_used else "none"
        print(f"    {label}: {len(group_tests)} tests, {group_cases} cases (axes: {axes_str})")
        total_cases += group_cases
        total_parametrized += sum(1 for t in group_tests if t["parametrize"])

    print(f"\n  summary:")
    print(f"    total tests: {len(tests)}")
    print(f"    total cases: {total_cases}")
    print(f"    parametrized: {total_parametrized}/{len(tests)}")


# ══════════════════════════════════════════
# Parsers (check)
# ══════════════════════════════════════════

def _parse_mock_axes(filepath):
    axes = {}
    with open(filepath) as f:
        content = f.read()

    for match in re.finditer(r"^([A-Z][A-Z0-9_]*S)\s*=\s*\[", content, re.MULTILINE):
        var_name = match.group(1)
        if var_name.endswith("_IDS"):
            continue
        items = _count_list_items_ast(content, var_name)
        axes[_plural_to_singular(var_name.lower())] = items

    return axes


def _parse_test_functions(filepath):
    with open(filepath) as f:
        content = f.read()

    try:
        tree = ast.parse(content)
    except SyntaxError:
        print(f"Warning: could not parse {filepath}", file=sys.stderr)
        return []

    tests = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
            tests.append({"name": node.name, "parametrize": _extract_parametrize(node.decorator_list)})
        elif isinstance(node, ast.ClassDef) and node.name.startswith("Test"):
            for method in node.body:
                if isinstance(method, ast.FunctionDef) and method.name.startswith("test_"):
                    tests.append({
                        "name": f"{node.name}::{method.name}",
                        "class": node.name,
                        "parametrize": _extract_parametrize(method.decorator_list),
                    })
    return tests


def _extract_parametrize(decorators):
    parametrize = {}
    for dec in decorators:
        if not isinstance(dec, ast.Call):
            continue
        func = dec.func
        if isinstance(func, ast.Attribute) and func.attr == "parametrize":
            if dec.args and isinstance(dec.args[0], ast.Constant):
                param_name = dec.args[0].value
                if len(dec.args) > 1 and isinstance(dec.args[1], ast.Name):
                    parametrize[param_name] = dec.args[1].id
    return parametrize


def _count_list_items_ast(content, var_name):
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id == var_name:
                if isinstance(node.value, ast.List):
                    return len(node.value.elts)
    return 0


def _detect_todos(d):
    todos = []
    for fname in ["mocks.py", "logic.py", "test_scenarios.py", "test_flows.py"]:
        fpath = d / fname
        if not fpath.exists():
            continue
        content = fpath.read_text()
        if "NotImplementedError" in content:
            todos.append(f"{fname}: has NotImplementedError")
        todo_count = content.count("# TODO")
        if todo_count:
            todos.append(f"{fname}: {todo_count} TODO(s)")
    return todos


# ══════════════════════════════════════════
# Helpers
# ══════════════════════════════════════════

def _slug(s):
    return re.sub(r"[^a-z0-9_]", "_", s.lower()).strip("_")


def _plural_to_singular(name):
    if name.endswith("ies"):
        return name[:-3] + "y"
    if name.endswith("ses") or name.endswith("xes") or name.endswith("zes"):
        return name[:-2]
    if name.endswith("s"):
        return name[:-1]
    return name


def _match_axis(param_name, var_name, axes):
    if param_name in axes:
        return param_name
    if var_name:
        derived = _plural_to_singular(var_name.lower())
        if derived in axes:
            return derived
    return None


def _sanitize_dir(p):
    sanitized = p.name.replace("-", "_")
    if sanitized != p.name:
        print(f"note: renamed '{p.name}' → '{sanitized}' (Python package)")
        return p.parent / sanitized
    return p


def _find_test_file(d):
    for name in ["test_scenarios.py", "test_flows.py"]:
        path = d / name
        if path.exists():
            return path
    _die(f"test file not found in {d}")


def _die(msg):
    print(f"Error: {msg}", file=sys.stderr)
    sys.exit(1)


def _count_combos(scenario):
    return math.prod(len(a.get("items", [])) for a in scenario.get("axes", []))


# ══════════════════════════════════════════
# CLI
# ══════════════════════════════════════════

def main():
    if len(sys.argv) < 2:
        print(__doc__.strip())
        sys.exit(1)

    command = sys.argv[1]

    if command == "init":
        if len(sys.argv) < 3:
            _die("Usage: generate.py init <config.json | ->")
        source = sys.argv[2]
        config = json.load(sys.stdin) if source == "-" else json.load(open(source))
        cmd_init(config)

    elif command == "check":
        if len(sys.argv) < 3:
            _die("Usage: generate.py check <test_dir>")
        cmd_check(sys.argv[2])

    else:
        _die(f"Unknown command: {command}. Commands: init, check")


if __name__ == "__main__":
    main()
